<?php
/****************************************************************************
 | Chamilo for Übercart
 |  An integration module between Drupal/Übercart and Chamilo
 | --------------------------------------------------------------------------
 | Main module definition
 | --------------------------------------------------------------------------
 | (c) Copyright 2013, BeezNest Belgium SPRL (info@beeznest.com)
 | (c) Copyright 2013, frenoy.net (info@frenoy.net)
 | --------------------------------------------------------------------------
 | Chamilo for Übercart is free software; you can redistribute it and/or
 | modify it under the terms of the GNU General Public License as published
 | by the Free Software Foundation; either version 2 of the License, or
 | (at your option) any later version.
 |
 | This program is distributed in the hope that it will be useful,
 | but WITHOUT ANY WARRANTY; without even the implied warranty of
 | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 | GNU General Public License for more details.
 |
 | You should have received a copy of the GNU General Public License
 | along with Chamilo for Übercart (see LICENSE.txt).
 | If not, see <http://www.gnu.org/licenses/>.
 ****************************************************************************/

/**
 * Implementation of hook_perm()
 * 
 * Define user permissions
 */
function uc_chamilo_perm() {
  return array(
    // User have full administrative rights on uc_chamilo parameters
    'administer uc_chamilo'
  );
}

/**
 * Implementation of hook_menu()
 *
 * Define menu items and page callbacks
 */
function uc_chamilo_menu() {
  $items['admin/store/settings/chamilo'] = array(
    'title'            => 'Chamilo',
    'description'      => 'Settings of the Chamilo for Übercart integration',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('uc_chamilo_admin'),
    'access arguments' => array('administer uc_chamilo'),
    'file'             => 'uc_chamilo.admin.inc'
  );
  return $items;
}

 ?>